# Generated by Django 5.2.17 on 2026-08-22 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedportfolio',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Who saved it. Null = legacy row from before accounts; claimed by whoever edits it next.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
    ]
