# Generated by Django 5.2.17 on 2026-08-22 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_savedportfolio_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My account', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw'), ('buy', 'buy'), ('sell', 'sell'), ('set_shares', 'set_shares'), ('set_cash', 'set_cash')], max_length=12)),
                ('ticker', models.CharField(blank=True, default='', max_length=10)),
                ('shares', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='explorer.account')),
            ],
            options={
                'ordering': ['date', 'created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AccountTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='explorer.account')),
            ],
            options={
                'ordering': ['-weight', 'ticker'],
                'constraints': [models.UniqueConstraint(fields=('account', 'ticker'), name='unique_target_per_account')],
            },
        ),
    ]
