# Generated by Django 5.2.17 on 2026-08-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_account_accountevent_accounttarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('cadence', models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('yearly', 'yearly')], default='monthly', max_length=10)),
                ('next_due', models.DateField()),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='explorer.account')),
            ],
        ),
    ]
